name: acs25-stage02

services:
  postgres:
    image: postgres:${POSTGRES_TAG}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  solr6:
    image: alfresco/alfresco-search-services:${SEARCH_SERVICES_TAG}
    environment:
      SOLR_ALFRESCO_HOST: alfresco
      SOLR_ALFRESCO_PORT: "8080"
      SOLR_SOLR_HOST: solr6
      SOLR_SOLR_PORT: "8983"
      SOLR_CREATE_ALFRESCO_DEFAULTS: alfresco,archive
      ALFRESCO_SECURE_COMMS: secret
      JAVA_TOOL_OPTIONS: >-
        -Dalfresco.secureComms.secret=secret
    ports:
      - "${SOLR_HTTP_PORT}:8983"
    volumes:
      - ./data/solr:/opt/alfresco-search-services/data

  alfresco:
    image: quay.io/alfresco/alfresco-content-repository:${ACS_TAG}
    depends_on:
      - postgres
      - solr6
    ports:
      - "${REPO_HTTP_PORT}:8080"
    environment:
      JAVA_TOOL_OPTIONS: >-
        -Dencryption.keystore.type=JCEKS
        -Dencryption.cipherAlgorithm=DESede/CBC/PKCS5Padding
        -Dencryption.keyAlgorithm=DESede
        -Dencryption.keystore.location=/usr/local/tomcat/shared/classes/alfresco/extension/keystore/keystore
        -Dmetadata-keystore.password=${METADATA_KEYSTORE_PASSWORD}
        -Dmetadata-keystore.aliases=metadata
        -Dmetadata-keystore.metadata.password=${METADATA_KEYSTORE_METADATA_PASSWORD}
        -Dmetadata-keystore.metadata.algorithm=DESede
      JAVA_OPTS: >-
        -Ddb.driver=org.postgresql.Driver
        -Ddb.username=${POSTGRES_USER}
        -Ddb.password=${POSTGRES_PASSWORD}
        -Ddb.url=jdbc:postgresql://postgres:5432/${POSTGRES_DB}
        -Dindex.subsystem.name=solr6
        -Dsolr.host=solr6
        -Dsolr.secureComms=secret
        -Dsolr.sharedSecret=secret
        -Dalfresco.events.include=
        -Dmessaging.subsystem.autoStart=false
        -Dlocal.transform.service.enabled=false
        -Dcsrf.filter.enabled=false
        -Ddeployment.method=DOCKER_COMPOSE
        -Dalfresco.host=localhost
        -Dalfresco.port=${REPO_HTTP_PORT}
        -Dalfresco.protocol=http
    volumes:
      - ./data/alf_data:/usr/local/tomcat/alf_data
