name: acs25-stage04

services:
  postgres:
    image: postgres:${POSTGRES_TAG}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  solr6:
    image: alfresco/alfresco-search-services:${SEARCH_SERVICES_TAG}
    environment:
      SOLR_ALFRESCO_HOST: alfresco
      SOLR_ALFRESCO_PORT: "8080"
      SOLR_SOLR_HOST: solr6
      SOLR_SOLR_PORT: "8983"
      SOLR_CREATE_ALFRESCO_DEFAULTS: alfresco,archive
      ALFRESCO_SECURE_COMMS: secret
      JAVA_TOOL_OPTIONS: >-
        -Dalfresco.secureComms.secret=secret
    ports:
      - "${SOLR_HTTP_PORT}:8983"
    volumes:
      - ./data/solr:/opt/alfresco-search-services/data

  activemq:
    image: quay.io/alfresco/alfresco-activemq:${ACTIVEMQ_TAG}
    ports:
      - "${ACTIVEMQ_WEB_PORT}:8161"
    environment:
      ACTIVEMQ_USERNAME: ${ACTIVEMQ_USERNAME}
      ACTIVEMQ_PASSWORD: ${ACTIVEMQ_PASSWORD}

  shared-file-store:
    image: quay.io/alfresco/alfresco-shared-file-store:${SHARED_FILE_STORE_TAG}

  transform-core-aio:
    image: quay.io/alfresco/alfresco-transform-core-aio:${TRANSFORM_CORE_AIO_TAG}
    depends_on:
      - activemq
      - shared-file-store
    environment:
      ACTIVEMQ_URL: nio://activemq:61616
      ACTIVEMQ_USER: ${ACTIVEMQ_USERNAME}
      ACTIVEMQ_PASSWORD: ${ACTIVEMQ_PASSWORD}
      FILE_STORE_URL: http://shared-file-store:8099/alfresco/api/-default-/private/sfs/versions/1/file

  transform-router:
    image: quay.io/alfresco/alfresco-transform-router:${TRANSFORM_ROUTER_TAG}
    depends_on:
      - activemq
      - shared-file-store
      - transform-core-aio
    environment:
      ACTIVEMQ_URL: nio://activemq:61616
      CORE_AIO_URL: http://transform-core-aio:8090
      FILE_STORE_URL: http://shared-file-store:8099/alfresco/api/-default-/private/sfs/versions/1/file
      JAVA_OPTS: >-
        -Dqueue.engine.activemq.user=${ACTIVEMQ_USERNAME}
        -Dqueue.engine.activemq.password=${ACTIVEMQ_PASSWORD}

  alfresco:
    image: quay.io/alfresco/alfresco-content-repository:${ACS_TAG}
    depends_on:
      - postgres
      - solr6
      - activemq
      - transform-router
    ports:
      - "${REPO_HTTP_PORT}:8080"
    environment:
      JAVA_TOOL_OPTIONS: >-
        -Dencryption.keystore.type=JCEKS
        -Dencryption.cipherAlgorithm=DESede/CBC/PKCS5Padding
        -Dencryption.keyAlgorithm=DESede
        -Dencryption.keystore.location=/usr/local/tomcat/shared/classes/alfresco/extension/keystore/keystore
        -Dmetadata-keystore.password=${METADATA_KEYSTORE_PASSWORD}
        -Dmetadata-keystore.aliases=metadata
        -Dmetadata-keystore.metadata.password=${METADATA_KEYSTORE_METADATA_PASSWORD}
        -Dmetadata-keystore.metadata.algorithm=DESede
      JAVA_OPTS: >-
        -Ddb.driver=org.postgresql.Driver
        -Ddb.username=${POSTGRES_USER}
        -Ddb.password=${POSTGRES_PASSWORD}
        -Ddb.url=jdbc:postgresql://postgres:5432/${POSTGRES_DB}
        -Dindex.subsystem.name=solr6
        -Dsolr.host=solr6
        -Dsolr.secureComms=secret
        -Dsolr.sharedSecret=secret
        -Dmessaging.broker.url="failover:(nio://activemq:61616)?timeout=3000&jms.useCompression=true"
        -Dmessaging.broker.username=${ACTIVEMQ_USERNAME}
        -Dmessaging.broker.password=${ACTIVEMQ_PASSWORD}
        -Dtransform.service.enabled=true
        -Dtransform.service.url=http://transform-router:8095
        -Dsfs.url=http://shared-file-store:8099/
        -Dlegacy.transform.service.enabled=false
        -DlocalTransform.core-aio.url=http://transform-core-aio:8090/
        -Dcsrf.filter.enabled=false
        -Ddeployment.method=DOCKER_COMPOSE
        -Dalfresco.host=localhost
        -Dalfresco.port=${REPO_HTTP_PORT}
        -Dalfresco.protocol=http
    volumes:
      - ./data/alf_data:/usr/local/tomcat/alf_data
